# Generated by Django 5.0.2 on 2024-03-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='autoseg_user',
        ),
    ]
