# NOTE: The labels are as per harmonization scheme
ALL_SEG_MAP = {
    "TSPrime": {
        1: "body",
        2: "bladder",
        3: "anorectum",
        4: "bag_bowel",
        5: "femur_head_l",
        6: "femur_head_r",
        7: "penile bulb",
        8: "ctvp",
        9: "ctvn",
    },
    "TSGyne": {
        1: "Bladder",
        2: "Bag_Bowel",
        3: "SpinalCord",
        4: "Duodenum",
        5: "Pancreas",
        6: "Rectum",
        7: "Colon_Sigmoid",
        8: "Body",
        9: "Vs_Int_Iliac",
        10: "Vs_Common_Iliac",
        11: "Vs_Ext_Iliac",
        12: "Vagina",
        13: "V_Venacava_I",
        14: "Stomach",
        15: "Spleen",
        16: "Liver",
        17: "Kidney_R",
        18: "Kidney_L",
        19: "Femur_R",
        20: "Femur_L",
        21: "Ctvn_Presacral",
        22: "Ctvn_Paraaortic",
        23: "Ctvn_Obturator",
        24: "Ctvn_Int_Iliac",
        25: "Ctvn_Ext_Iliac",
        26: "Ctvn_Com_Iliac",
        27: "Bowel",
        28: "Bone_Marrow_Pel",
        29: "Bone_Marrow_Lum",
        30: "Anus",
        31: "A_Aorta",
    },
}
