"""init migrate

Revision ID: f96cec72760a
Revises:
Create Date: 2024-01-03 13:13:50.444604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f96cec72760a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dicomlog",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("series_name", sa.String(length=256), nullable=True),
        sa.Column("input_path", sa.String(length=1024), nullable=True),
        sa.Column("output_path", sa.String(length=1024), nullable=True),
        sa.Column(
            "status",
            sa.Enum("INIT", "STARTED", "PREDICTED", "SENT", name="status"),
            server_default="INIT",
            nullable=True,
        ),
        sa.Column("model", sa.Enum("TSGyne", "TSPrime", name="model"), nullable=True),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dicomlog_status"), "dicomlog", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dicomlog_status"), table_name="dicomlog")
    op.drop_table("dicomlog")
    # ### end Alembic commands ###
